### ISSUE TITLE
Add support for governor

### ISSUE THREAD

**Issue by mmdmine** [martin31821/cpupower#147] opened 2021-02-19 15:45 UTC
Please add support for setting cpu governor.
My current cpu has two governors: performance and powersave.
with this extension, it's always on powersave, and I should set it to performance manually using `# cpupower frequency-set -g performance`.

**Comment by fin-ger** [comment] 2021-02-19 15:55
Duplicate of #68

**Closed by fin-ger** 2021-02-19 15:55 UTC

**Comment by mmdmine** [comment] 2021-02-20 15:27
Ok sorry

**Comment by fin-ger** [comment] 2021-02-20 15:29
no problem :smile:
