### ISSUE TITLE
Does not work on fedora silverblue, as default prefix /usr is a read-only directory.

### ISSUE THREAD

**Issue by varunmittal91** [martin31821/cpupower#129] opened 2020-07-27 14:19 UTC
Under fedora silverblue, being an ostree based distribution, the extension does not work.
Similar operating systems where this behavior would be noticed are fedora continuous and kde neon.

In the install script under the dropdown, we need to create an option for prefix and save that so that it can be modified by the user.

**Comment by martin31821** [comment] 2020-07-27 14:25
duplicate of https://github.com/martin31821/cpupower/issues/83.
While we have the option to install into another prefix, this is something a package maintainer in silverblue would need to handle.

**Closed by martin31821** 2020-07-27 14:25 UTC
