### ISSUE TITLE
It hangs my GNOME 3.16

### ISSUE THREAD

**Issue by steelbrain** [martin31821/cpupower#11] opened 2015-05-27 22:08 UTC
It hangs immediately after it, the TTY{X} works though. Moving the cursor works as well, nothing else does. GDM works too. Restarting doesn't help so I removed the extension from FS.

**Comment by martin31821** [comment] 2015-05-30 07:13
Can you include some logs from GNOME? (especially the output of `journalctl -xb`

**Comment by stuaxo** [comment] 2015-06-16 07:56
Just confirming I had something similar to this .... worked, but I hadn't copied in the external tools yet ... copied them in and gnome shell just hung on launch.

Can upload the journalctl -xb output somewhere, its 1.5mb ...

**Comment by martin31821** [comment] 2015-07-18 17:23
This problem should be fixed as of V2, as no more installation of cpufreqctl is required. 
If you can confirm this, please close this issue.

**Comment by spacepluk** [comment] 2015-07-19 11:59
I'm having the same problem, and I just tried the last commit in master but it still hangs.

**Comment by mumblyOMOD** [comment] 2015-07-20 02:12
I can confirm. I have the exact same symptoms as the original poster.  I've tried installing from the most recent master on git and from extensions.gnome.org.  I'm running Gnome Shell 3.16.2 on OpenSUSE Tumbleweed.  The only line from journalctl -xb that looks related to this plugin is this: Gjs-Message: JS LOG: sed -i "s/xxxPATHxxx/\/home\/omod\/\.local\/share\/gnome-shell\/extensions\/cpupower@mko-sl\.de\/cpufreqctl/" /home/omod/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/mko.cpupower.policy

**Comment by martin31821** [comment] 2015-07-20 07:34
yes, that is correct. So did you remove cpufreqctl from /usr/local/bin or whereever you installed it?
cpufreqctl **must not** be installed system-wide as it is executed from within the extensions directory.

I tested it yesterday on fedora, worked like a charm.

@mumblyOMOD - Can you copy  /home/omod/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/mko.cpupower.policy  to /usr/share/polkit-1/actions and then restart gnome-shell?

**Comment by spacepluk** [comment] 2015-07-20 07:57
Arch Linux here with Gnome 3.16.2.  `cpufreqctl` is not in the PATH and mko.cpupower.policy is in place, but it still freezes.  Is there anything I can do to help you debug this?

**Comment by martin31821** [comment] 2015-07-20 11:42
Points you can check:
* mko.cpupower.policy contains the right path to cpufreqctl (should be ~/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/cpufreqctl)
* you can execute `pkexec ~/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/cpufreqctl max 100`, this should work 
* you could try the experimental branch, where I changed some command line handling (should only affect the first installation)

I will try to reproduce this on a bunch of distros

**Comment by stuaxo** [comment] 2015-07-20 11:45
Is there no way it can check for the failure modes and show that it failed in its ui somehow ?

**Comment by spacepluk** [comment] 2015-07-20 11:53
@martin31821 I checked the first two points, and everything seems to be fine.  pkexec asks for the password (via gnome-shell) and then it changes the frequency correctly.

I'll try the experimental branch later and let you know how it goes.

**Comment by martin31821** [comment] 2015-07-20 11:56
@spacepluk thats the problem!

when gnome-shell is starting, pkexec can't create the window to ask you for the password, but blocks the process, which prevents gnome-shell from finishing the startup.
It should execute without any user interaction (i.e. policykit should permit the execution, without asking you)

**Comment by stuaxo** [comment] 2015-07-20 12:01
So I guess it needs to either wait until gnome-shell has started, or just not run at all if it doesn't have permission.

**Comment by spacepluk** [comment] 2015-07-20 13:02
@martin31821 I don't know, for me it also hangs if I install from firefox with gnome-shell already running :?

Arch has polkit 0.112 if that helps.

**Comment by martin31821** [comment] 2015-07-20 14:12
@spacepluk - I assume you flushed the policykit cache (done through restarting polkit.service if you use systemd)?

**Comment by mumblyOMOD** [comment] 2015-07-20 16:37
@martin31821 - I was able to get your extension working by copying /home/omod/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/mko.cpupower.policy to /usr/share/polkit-1/actions manually, at which point the extension would still cause gnome-shell to hang.  I then commented out line 156 [GLib.spawn_command_line_sync('xdg-open ' + EXTENSIONDIR + '/installation');] in extension.js which lets gnome run normally with your extension working perfectly.  So it looks like your extension was hanging on that one line on my system, for some reason.

**Comment by spacepluk** [comment] 2015-07-20 17:03
@mumblyOMOD cool! I just tried that and now it works :) :+1:

**Comment by martin31821** [comment] 2015-07-20 19:31
Please try the latest experimental branch, and confirm the solution.

**Comment by mumblyOMOD** [comment] 2015-07-20 19:47
I removed the extension and the policy from /usr/share/polkit-1/actions, then reinstalled the experimental branch from git.  The experimental branch works perfectly.  Thanks for the quick fix. :+1:

**Closed** 2015-07-20 19:49 UTC
Labels: bug

**Comment by steelbrain** [comment] 2015-07-20 19:58
I can confirm that the fix works <3 <3 <3 <3

**Comment by spacepluk** [comment] 2015-07-20 20:08
great, thank you!
